name: jaguar_cors_demo
description: A demo of handling CORS using Jaguar
version: 0.0.1

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  jaguar: ^0.6.13
  jaguar_cors: ^0.5.3
  jaguar_client:
  # cookies:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

web:
  compiler:
    debug: dartdevc

