name: jaguar_cors_demo
description: A demo of handling CORS using Jaguar
version: 0.0.1

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  jaguar: ^0.6.13
  jaguar_cors:
  jaguar_client:
  # cookies:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc

