name: jaguar_cors_demo
description: A demo of handling CORS using Jaguar
version: 2.4.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.1
  jaguar_cors: ^2.4.2
  jaguar_client:
  jaguar_reflect:

dev_dependencies:
